In [9]:
# !pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 5.0 MB/s 


In [15]:
# !pip uninstall transformers

Found existing installation: transformers 4.22.1
Uninstalling transformers-4.22.1:
  Would remove:
    /usr/local/bin/transformers-cli
    /usr/local/lib/python3.7/dist-packages/transformers-4.22.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/transformers/*
Proceed (y/n)? y
  Successfully uninstalled transformers-4.22.1


In [16]:
!pip install --no-cache-dir transformers sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.9 MB 5.1 MB/s 


In [3]:
# !pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import pandas as pd

import torch
from transformers import BertTokenizer, BertModel

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)

import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
# https://huggingface.co/ai4bharat/indic-bert
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('ai4bharat/indic-bert', keep_accents=True)
model = AutoModel.from_pretrained('ai4bharat/indic-bert')

Some weights of the model checkpoint at ai4bharat/indic-bert were not used when initializing AlbertModel: ['sop_classifier.classifier.bias', 'predictions.decoder.bias', 'predictions.dense.bias', 'predictions.bias', 'predictions.decoder.weight', 'predictions.LayerNorm.bias', 'predictions.LayerNorm.weight', 'predictions.dense.weight', 'sop_classifier.classifier.weight']
- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [9]:
text = "அமைச்சின் பணிகளை முன்னெடுப்பதற்கு கௌர அமைச்சர் வாசுதேவ நாணாயக்கார அவர்களுக்கு தத்துவம் வழங்கப்பட்டதுடன் திருமதி எம்  எஸ்  விக்கிரமசிங்க அமைச்சின் செயலாளராக செயலாற்றுகிறார் "
marked_text = "[CLS] " + text + " [SEP]"

# Tokenize our sentence with the BERT tokenizer.
tokenized_text = tokenizer.tokenize(marked_text)

# Print out the tokens.
print (tokenized_text)

['[CLS]', '▁அமைச்ச', 'ின்', '▁பணிகளை', '▁முன்னெடுப்ப', 'தற்கு', '▁கௌ', 'ர', '▁அமைச்சர்', '▁வாசுதேவ', '▁நாண', 'ாய', 'க்கார', '▁அவர்களுக்கு', '▁தத்துவம்', '▁வழங்கப்பட்டது', 'டன்', '▁திருமதி', '▁எம்', '▁எஸ்', '▁விக்கிரமசிங்க', '▁அமைச்ச', 'ின்', '▁செயலாளராக', '▁செயலாற்ற', 'ுகிறார்', '▁', '[SEP]']


In [10]:
# Map the token strings to their vocabulary indeces.
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Display the words with their indeces.
for tup in zip(tokenized_text, indexed_tokens):
  print('{:<12} {:>6,}'.format(tup[0], tup[1]))

[CLS]             2
▁அமைச்ச      31,173
ின்             437
▁பணிகளை      28,327
▁முன்னெடுப்ப 100,858
தற்கு         9,575
▁கௌ          98,792
ர             5,798
▁அமைச்சர்     2,731
▁வாசுதேவ     132,499
▁நாண         144,746
ாய           52,293
க்கார        43,205
▁அவர்களுக்கு  8,307
▁தத்துவம்    142,397
▁வழங்கப்பட்டது 35,669
டன்           5,986
▁திருமதி     65,618
▁எம்          2,809
▁எஸ்          3,393
▁விக்கிரமசிங்க 75,137
▁அமைச்ச      31,173
ின்             437
▁செயலாளராக   84,269
▁செயலாற்ற    126,357
ுகிறார்      11,230
▁                 8
[SEP]             3


## Sentence vectore

## Method 2

bert-base-multilingual-cased

In [13]:
import pandas as pd
import numpy as np

In [11]:
import transformers
from transformers import BertTokenizer, TFBertModel

In [12]:
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-multilingual-uncased', do_lower_case=True)
bert_model = transformers.TFBertModel.from_pretrained('bert-base-multilingual-uncased')

Downloading:   0%|          | 0.00/872k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/999M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-multilingual-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-multilingual-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [14]:
def bert_encode(data, maximum_length) :
  input_ids = []
  attention_masks = []
  
  for i in range(len(data)):
    encoded = tokenizer.encode_plus(      
      data[i],
      add_special_tokens=True,
      max_length=maximum_length,
      pad_to_max_length=True,
    
      return_attention_mask=True,      
    )
  
    input_ids.append(encoded['input_ids'])
    attention_masks.append(encoded['attention_mask'])
  
  return np.array(input_ids),np.array(attention_masks)

In [15]:
data = [
  'அமைச்சின் பணிகளை முன்னெடுப்பதற்கு கௌர அமைச்சர் வாசுதேவ நாணாயக்கார அவர்களுக்கு தத்துவம் வழங்கப்பட்டதுடன் திருமதி எம்  எஸ்  விக்கிரமசிங்க அமைச்சின் செயலாளராக செயலாற்றுகிறார்',
  'இவ்வமைச்சு இல 40  புத்கமுவ வீதி  இராஜகிரிய எனும் முகவரியில் அமையப்பெற்றுள்ளது',
  'தேசிய மொழிகள் மற்றும் சமூக ஒருமைப்பாட்டு அமைச்சின் அதிகாரங்கள் மற்றும் செயற்பாடுகள்',
  'தேசிய மொழிகள்  சமூக ஒருமைப்பாடு தொடர்பான கொள்கைகள் நிகழ்ச்சித் திட்டங்களையும் கருத்திட்டங்களையும் வகுத்தமைத்தல்',
  'குறித்த தேசிய நோக்கங்களை எய்தும் பொருட்டு தேசிய திட்டமிடல் அதிகாரிகளுடன் உடன்பட்ட செயற்பாட்டு எல்லைகுள்ளும் வரவு செலவுத் திட்டத்தில் அடங்கப்பெற்ற வளங்களை விஞ்சாதவாறும் சொல்லப்பட்ட கொள்கைகளையும் நிகழ்ச்சித்திட்டங்களையும் கருத்திட்டங்களையும் செயற்படுத்தலும் நெறிப்படுத்தலும்',
  'சமூக ஒருமைப்பாடும் இனங்களுடனான அலுவல்களும்'
]
  
# Create the pandas DataFrame with column name is provided explicitly
df = pd.DataFrame(data, columns=['news'])
  
# print dataframe.
df

news
0  அமைச்சின் பணிகளை முன்னெடுப்பதற்கு கௌர அமைச்சர்...
1  இவ்வமைச்சு இல 40  புத்கமுவ வீதி  இராஜகிரிய எனு...
2  தேசிய மொழிகள் மற்றும் சமூக ஒருமைப்பாட்டு அமைச்...
3  தேசிய மொழிகள்  சமூக ஒருமைப்பாடு தொடர்பான கொள்க...
4  குறித்த தேசிய நோக்கங்களை எய்தும் பொருட்டு தேசி...
5         சமூக ஒருமைப்பாடும் இனங்களுடனான அலுவல்களும்

In [19]:
# df['news'].str.len(), 
df['news'].str.len().max()

272

In [21]:
train_input_ids, train_attention_masks = bert_encode(df['news'], 300)

In [22]:
#Visualize the attention masks and input ids.
train_attention_masks, train_input_ids

(array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]]),
 array([[  101,   789, 29955, ...,     0,     0,     0],
        [  101,   791, 26577, ...,     0,     0,     0],
        [  101, 34213, 73141, ...,     0,     0,     0],
        [  101, 34213, 73141, ...,     0,     0,     0],
        [  101,   800, 18619, ...,     0,     0,     0],
        [  101,   802, 12005, ...,     0,     0,     0]]))

In [34]:
#Build a miniature model for extracting the embeddings
import tensorflow as tf
# from tensorflow.keras.layers import LSTM, Dense,Flatten,Conv2D,Conv1D,GlobalMaxPooling1D
# from tensorflow.keras import layers

from keras.models import Sequential, Model
# # from keras.optimizers import Adam
# from keras.models import Sequential
# from keras.layers.recurrent import LSTM, GRU
# from keras.layers.core import Dense, Activation, Dropout
# from keras.layers.embeddings import Embedding
# # from keras.layers.normalization import BatchNormalization
# from keras.utils import np_utils

In [35]:
input_ids = tf.keras.layers.Input(shape=(128,), name='input_token', dtype='int32')
input_masks_ids = tf.keras.layers.Input(shape=(128,), name='masked_token', dtype='int32')

bert_output = bert_model([input_ids, input_masks_ids])[0]
bert_output.shape
bert_output[:,0,:]

model = Model(inputs=[input_ids, input_masks_ids],outputs = [bert_output])
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_token (InputLayer)       [(None, 128)]        0           []                               
                                                                                                  
 masked_token (InputLayer)      [(None, 128)]        0           []                               
                                                                                                  
 tf_bert_model (TFBertModel)    TFBaseModelOutputWi  167356416   ['input_token[0][0]',            
                                thPoolingAndCrossAt               'masked_token[0][0]']           
                                tentions(last_hidde                                               
                                n_state=(None, 128,                                         

In [36]:
#Use the tokenizer and model  from the Transformers and determine the output features from the last hidden layer.
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

def get_embeddings(model_name,tokenizer,name,inp):
  tokenizer = tokenizer.from_pretrained(name)
  model = model_name.from_pretrained(name)

  input_ids = tf.constant(tokenizer.encode(inp))[None, :]  # Batch size 1
  outputs = model(input_ids)

  last_hidden_states = outputs[0]
  cls_token=last_hidden_states[0]
  
  return cls_token

In [29]:
z = df['news'].tolist()

In [31]:
z[0]

'அமைச்சின் பணிகளை முன்னெடுப்பதற்கு கௌர அமைச்சர் வாசுதேவ நாணாயக்கார அவர்களுக்கு தத்துவம் வழங்கப்பட்டதுடன் திருமதி எம்  எஸ்  விக்கிரமசிங்க அமைச்சின் செயலாளராக செயலாற்றுகிறார்'

In [37]:
cls_token = get_embeddings(TFBertModel, BertTokenizer, 'bert-base-multilingual-uncased', z[0])
cls_token

Some layers from the model checkpoint at bert-base-multilingual-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-multilingual-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


<tf.Tensor: shape=(71, 768), dtype=float32, numpy=
array([[-0.10861358, -0.06730223,  0.07388302, ...,  0.04361111,
        -0.04630373, -0.06499264],
       [ 0.05621428,  0.11254698, -0.0088466 , ..., -0.03384805,
         0.10702873, -0.42685288],
       [-0.35092622, -0.83444476,  0.6366284 , ...,  0.19836532,
        -0.6008336 , -0.12423165],
       ...,
       [-0.4456465 , -0.3897203 ,  0.796821  , ...,  0.70930153,
        -0.54098004, -1.0375787 ],
       [ 0.08041987,  0.01899316,  0.2989576 , ...,  1.0375788 ,
        -0.54234517, -0.49848205],
       [-0.30701053,  0.23436832,  0.26524258, ...,  0.576362  ,
         0.04702273, -0.7759421 ]], dtype=float32)>